main: me.chandl.cfminigame.CFMinigame
name: CFMinigame
version: 1.0
author: Chandler Severson
description: A Minigame Plugin for Creative Freebuild Server
commands:
   mg:
      description: The main CFMinigame command.
      usage: /mg
permissions:
  CFMinigame.mg.*:
     description: Gives access to all minigame commands.
  CFMinigame.mg.admin:
     description: Gives access to all admin minigame commands.
     children:
        CFMinigame.mg.stop: true
  CFMinigame.mg.user:
     description: Gives access to all user minigame commands
     children:
        CFMinigame.mg.playerlist: true
        CFMinigame.mg.help: true
        CFMinigame.mg.highscore: true
        CFMinigame.mg.leave: true
        CFMinigame.mg.join: true
        CFMinigame.mg.start: true
  CFMinigame.mg.playerlist:
     description: Shows the player list.
  CFMinigame.mg.help:
     description: Shows help for plugin.
  CFMinigame.mg.highscore:
     description: Shows the high scores.
  CFMinigame.mg.leave:
     description: Leave a game.
  CFMinigame.mg.join:
     description: Join a game.
  CFMinigame.mg.start:
     description: Start a game.